# Generated by Django 3.2.15 on 2022-08-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
