# Generated by Django 3.2.15 on 2022-09-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220912_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
