# Generated by Django 3.2.15 on 2022-09-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GM_Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event.profile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
