# Generated by Django 3.2.15 on 2022-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_delete_groupchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
