# Generated by Django 3.2.15 on 2022-09-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_gm_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gm_promotion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gm_promotion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_requests', to='event.profile'),
        ),
    ]
