# Generated by Django 3.2.15 on 2022-08-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='excerpt',
        ),
    ]
