# Generated by Django 3.2.15 on 2022-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='character_max',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4),
        ),
    ]
