# Generated by Django 3.2.15 on 2022-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20220901_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='snippet',
            field=models.CharField(default='Chick the event title above for more...', max_length=300),
        ),
    ]
