# Generated by Django 3.2.15 on 2022-09-18 17:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character_class', models.CharField(max_length=200)),
                ('background', models.TextField(blank=True, null=True)),
                ('background_snippet', models.CharField(blank=True, max_length=300, null=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('items', models.TextField(blank=True, null=True)),
                ('equipt_head', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_face', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_shoulder_left', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_shoulder_right', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_torso', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_back', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_hand_left', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_hand_right', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_waist', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_legs', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_feet', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_one', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_two', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_three', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_four', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_five', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_accessory_six', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_main_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('equipt_off_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_note', to='character.character')),
            ],
        ),
    ]
