# Generated by Django 3.2.15 on 2022-09-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='equipment',
        ),
        migrations.AddField(
            model_name='character',
            name='background_snippet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=300, null=True)),
                ('face', models.CharField(blank=True, max_length=300, null=True)),
                ('shoulder_left', models.CharField(blank=True, max_length=300, null=True)),
                ('shoulder_right', models.CharField(blank=True, max_length=300, null=True)),
                ('torso', models.CharField(blank=True, max_length=300, null=True)),
                ('back', models.CharField(blank=True, max_length=300, null=True)),
                ('hand_left', models.CharField(blank=True, max_length=300, null=True)),
                ('hand_right', models.CharField(blank=True, max_length=300, null=True)),
                ('waist', models.CharField(blank=True, max_length=300, null=True)),
                ('legs', models.CharField(blank=True, max_length=300, null=True)),
                ('feet', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_one', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_two', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_three', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_four', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_five', models.CharField(blank=True, max_length=300, null=True)),
                ('accessory_six', models.CharField(blank=True, max_length=300, null=True)),
                ('main_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('off_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_equipment', to='character.character')),
            ],
        ),
    ]
