# Generated by Django 3.2.15 on 2022-08-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='slug',
        ),
    ]
