# Generated by Django 3.2.15 on 2022-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_equipment_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_five',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_four',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_one',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_six',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_three',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_accessory_two',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_back',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_face',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_feet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_hand_left',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_hand_right',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_head',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_legs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_main_hand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_off_hand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_shoulder_left',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_shoulder_right',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_torso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipt_waist',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
